/**
 * Curated themed word lists for Word Search puzzles.
 * Each theme contains over 100 high-quality, uppercase English words
 * (length 4–9) selected for varied puzzle generations.
 */

export const WORD_SEARCH_THEMES = [
  'Space',
  'Animals',
  'Ocean & Deep Sea',
  'Food & Cooking',
  'Computing & Tech',
  'Mythology & Fantasy',
  'Sports & Games',
  'Music & Audio',
  'Weather & Seasons',
  'World & Travel',
] as const;

export type WordSearchTheme = (typeof WORD_SEARCH_THEMES)[number];

export const THEMED_WORD_BANKS: Record<string, string[]> = {
  space: [
    'ASTRONAUT', 'ASTEROID', 'ECLIPSE', 'GALAXY', 'JUPITER', 'METEOR', 'NEBULA', 'ORBIT', 'PLANET', 'PULSAR',
    'QUASAR', 'ROCKET', 'SATURN', 'SHUTTLE', 'SOLAR', 'STAR', 'SUNSPOT', 'VENUS', 'MERCURY', 'MARS',
    'URANUS', 'NEPTUNE', 'PLUTO', 'COSMOS', 'AURORA', 'GRAVITY', 'CRATER', 'APOGEE', 'ZENITH', 'NADIR',
    'CORONA', 'FLARE', 'ORBITER', 'LANDER', 'ROVER', 'NOVA', 'COMET', 'STARDUST', 'VACUUM', 'VOYAGER',
    'HUBBLE', 'APOLLO', 'ARTEMIS', 'HELIOS', 'PHOTON', 'HORIZON', 'SPHERE', 'PAYLOAD', 'BOOSTER', 'THRUSTER',
    'AIRLOCK', 'CAPSULE', 'MODULE', 'STATION', 'DOCKING', 'REENTRY', 'BEACON', 'RADAR', 'ANTENNA', 'SPECTRAL',
    'RADIAN', 'CLUSTER', 'VOID', 'DWARF', 'GIANT', 'SPICULE', 'ALBEDO', 'AZIMUTH', 'RADIO', 'OPTICAL',
    'COSMOLOGY', 'POLARIS', 'ANDROMEDA', 'CELESTIAL', 'MAGNETAR', 'PARALLAX', 'PERIGEE', 'SOLSTICE', 'EQUINOX',
    'ZODIAC', 'PROPULSION', 'TRAJECTORY', 'TELEMETRY', 'EXOPLANET', 'PROTOSTAR', 'RETROGRADE', 'PROGRADE',
    'ALTITUDE', 'AERO', 'IONOSPHERE', 'STARLIGHT', 'SUPERNOVA', 'CRUCIS', 'ORION', 'SIRIUS', 'VEGA',
    'RIGEL', 'BETELGEUSE', 'CYGNUS', 'CASSIOPEIA', 'DRACO', 'PEGASUS', 'CENTAURUS', 'GEMINI', 'SAGITTARIUS',
  ],

  animals: [
    'ELEPHANT', 'GIRAFFE', 'KANGAROO', 'LEOPARD', 'CHEETAH', 'DOLPHIN', 'PENGUIN', 'FLAMINGO', 'HAMSTER', 'HEDGEHOG',
    'MEERKAT', 'OSTRICH', 'PANTHER', 'RACCOON', 'SEAGULL', 'SQUIRREL', 'TORTOISE', 'VULTURE', 'WALRUS', 'WOMBAT',
    'BUFFALO', 'GAZELLE', 'GORILLA', 'HYENA', 'IGUANA', 'KOALA', 'LEMUR', 'LIZARD', 'MONKEY', 'PELICAN',
    'PLATYPUS', 'TOUCAN', 'ZEBRA', 'ANTELOPE', 'BABOON', 'BADGER', 'BEAVER', 'COUGAR', 'COYOTE', 'DINGO',
    'DONKEY', 'FERRET', 'GIBBON', 'JAGUAR', 'LLAMA', 'LYNX', 'MARMOT', 'MOOSE', 'OCELOT', 'OTTER',
    'PANDA', 'POSSUM', 'REINDEER', 'SKUNK', 'SLOTH', 'TAPIR', 'VIPER', 'WEASEL', 'YAK', 'ALPACA',
    'ARMADILLO', 'CAPYBARA', 'DUGONG', 'ECHIDNA', 'EMU', 'ERMINE', 'FENNEC', 'GERBIL', 'GOPHER', 'GUANACO',
    'IBEX', 'IMPALA', 'JACKAL', 'JERBOA', 'KUDU', 'LEMMING', 'MANDRILL', 'MARKHOR', 'MINK', 'NARWHAL',
    'NUTRIA', 'OKAPI', 'ORYX', 'PANGOLIN', 'PECCARY', 'PUMA', 'QUOKKA', 'SERVAL', 'SHREW', 'SIFAKA',
    'TAMARIN', 'TARSIER', 'TAYRA', 'VICUNA', 'WALLABY', 'BISON', 'CARIBOU', 'CHIPMUNK', 'FOX', 'HARE',
    'MUSTELID', 'PUPPY', 'OTTER', 'BADGER', 'BOBCAT', 'BOAR', 'CAMEL', 'CHINCHILLA', 'GRIZZLY', 'MONGOOSE',
  ],

  'ocean & deep sea': [
    'ABYSS', 'ANCHOR', 'BARNACLE', 'BARRACUDA', 'BLOWHOLE', 'CORAL', 'CURRENT', 'DOLPHIN', 'DRIFTWOOD', 'FLOUNDER',
    'GULL', 'HARBOR', 'ISLET', 'JELLYFISH', 'KELP', 'KRILL', 'LAGOON', 'LOBSTER', 'MANATEE', 'MANTA',
    'MARLIN', 'MOLLUSK', 'NAUTILUS', 'OCTOPUS', 'OYSTER', 'PELICAN', 'PLANKTON', 'PORPOISE', 'REEF', 'SAILFISH',
    'SALMON', 'SEAGRASS', 'SEAGULL', 'SEAHORSE', 'SEAL', 'SEAWEED', 'SHARK', 'SHELL', 'SHRIMP', 'SPONGE',
    'SQUID', 'STARFISH', 'STINGRAY', 'TIDE', 'TRENCH', 'TSUNAMI', 'TURTLE', 'URCHIN', 'WALRUS', 'WAVE',
    'WHALE', 'WRECK', 'ANEMONE', 'ATOLL', 'CETACEAN', 'CLAM', 'COASTLINE', 'CONCH', 'CRAB', 'DIVER',
    'DUGONG', 'ESTUARY', 'FJORD', 'GULLY', 'HERRING', 'ICEBERG', 'ISOPOD', 'KNOT', 'LIMPET', 'MARITIME',
    'MAST', 'MEDUSA', 'NARWHAL', 'NEKTON', 'OCEANIC', 'PELAGIC', 'PINNIPED', 'RUDDER', 'SCALLOP', 'SCUBA',
    'SEAMOUNT', 'SHOAL', 'SIREN', 'SOUNDER', 'SWELL', 'TIDAL', 'TRIDENT', 'TUNA', 'UNDERTOW', 'VENT',
    'WHELK', 'SEABED', 'PELAGIC', 'BENTHIC', 'MARINER', 'SEAFARER', 'CORALLINE', 'ALGAE', 'MACKEREL', 'SNAPPER',
    'BARRACUDA', 'GROUPER', 'HALIBUT', 'SEALION', 'HUMPBACK', 'BELUGA', 'ORCA', 'BOWHEAD', 'ROQUAL', 'SEAWATER',
  ],

  'food & cooking': [
    'AVOCADO', 'BACON', 'BAKERY', 'BARBECUE', 'BASIL', 'BATTER', 'BISCUIT', 'BLENDER', 'BOIL', 'BROTH',
    'BUTTER', 'CABBAGE', 'CARAMEL', 'CHEDDAR', 'CHEESE', 'CHICKEN', 'CINNAMON', 'CLOVE', 'COCONUT', 'COFFEE',
    'COOKIE', 'CREAM', 'CUMIN', 'CURRY', 'CUSTARD', 'DESSERT', 'DOUGHNUT', 'DRESSING', 'DUMPLING', 'ESPRESSO',
    'FLAVOUR', 'FLOUR', 'FONDUE', 'FORK', 'FREEZER', 'GARLIC', 'GINGER', 'GOURMET', 'GRATER', 'GRILL',
    'GUMBO', 'HONEY', 'JELLY', 'KETTLE', 'KITCHEN', 'KNIFE', 'LADLE', 'LASAGNA', 'LEMON', 'MACARONI',
    'MANGO', 'MARINADE', 'MEATBALL', 'MUFFIN', 'MUSTARD', 'NOODLE', 'NUTMEG', 'OMELETTE', 'ONION', 'OREGANO',
    'PANCAKE', 'PANTRY', 'PAPRIKA', 'PASTA', 'PASTRY', 'PEPPER', 'PICKLE', 'PIZZA', 'PLATTER', 'POPCORN',
    'POTATO', 'PUDDING', 'RADISH', 'RECIPE', 'RISOTTO', 'ROAST', 'ROSEMARY', 'SAFFRON', 'SALAD', 'SALMON',
    'SAUCE', 'SAUSAGE', 'SKILLET', 'SPATULA', 'SPICE', 'SPINACH', 'STEAM', 'STEW', 'SUGAR', 'SYRUP',
    'TARRAGON', 'TOASTER', 'TOMATO', 'TORTILLA', 'TURMERIC', 'VANILLA', 'VINEGAR', 'WAFFLE', 'WALNUT', 'WHISK',
    'YOGURT', 'ZEST', 'BAGEL', 'BURGER', 'BURRITO', 'CASHEW', 'CHUTNEY', 'CORNBREAD', 'CROISSANT', 'FALAFEL',
  ],

  'computing & tech': [
    'ALGORITHM', 'BACKEND', 'BANDWIDTH', 'BINARY', 'BITCOIN', 'BOOLEAN', 'BOOTSTRAP', 'BROWSER', 'BUFFER', 'BYTECODE',
    'CACHE', 'CHIPSET', 'CIRCUIT', 'CLIENT', 'CLOUD', 'CODEBASE', 'COMMAND', 'COMPILER', 'CONSOLE', 'COOKIE',
    'CRYPTO', 'CURSOR', 'CYBER', 'DATABASE', 'DEBUGGER', 'DEPLOY', 'DESKTOP', 'DIGITAL', 'DISPLAY', 'DONGLE',
    'DRIVER', 'EMULATOR', 'ETHERNET', 'FIREWALL', 'FIRMWARE', 'FRONTEND', 'GATEWAY', 'GIGABYTE', 'GRAPHICS', 'HARDWARE',
    'HASHING', 'HOSTING', 'INTERNET', 'JOYSTICK', 'KERNEL', 'KEYBOARD', 'LATENCY', 'LINUX', 'LOGIC', 'MEGABYTE',
    'MEMORY', 'MODEM', 'MONITOR', 'NETWORK', 'NODE', 'OPTICAL', 'PACKET', 'PASSWORD', 'PHISHING', 'PIXEL',
    'PROCESSOR', 'PROGRAM', 'PROTOCOL', 'PYTHON', 'QUANTUM', 'RECOVERY', 'ROUTER', 'RUNTIME', 'SCANNER', 'SCRIPT',
    'SENSOR', 'SERVER', 'SOCKET', 'SOFTWARE', 'STORAGE', 'SYNTAX', 'TERMINAL', 'THREAD', 'TOUCHPAD', 'UNICODE',
    'UPLOAD', 'VARIABLE', 'VIRTUAL', 'VOLTAGE', 'WEBCAM', 'WIRELESS', 'CHIP', 'CODEC', 'DATABASE', 'DOMAIN',
    'DOCKER', 'FIREWIRE', 'FRAMEWORK', 'GIGABIT', 'GRAPHQL', 'HOTSPOT', 'HYPERVISOR', 'INTERFACE', 'ITERATOR', 'JSON',
    'KEYFRAME', 'LAN', 'LOOP', 'MICROCODE', 'MODULAR', 'MUTEX', 'NANOBOT', 'PACKAGING', 'PARSER', 'PIPELINE',
  ],

  'mythology & fantasy': [
    'ALCHEMIST', 'AMULET', 'ARCHMAGE', 'ARTIFACT', 'BASILISK', 'BEHEMOTH', 'CENTAUR', 'CERBERUS', 'CHIMERA', 'CYCLOPS',
    'DEMON', 'DRAGON', 'DRUID', 'DWARF', 'ELIXIR', 'FAIRY', 'FAMILIAR', 'GARGOYLE', 'GENIE', 'GHOUL',
    'GIANT', 'GNOME', 'GOBLIN', 'GOLEM', 'GRIFFIN', 'HARPY', 'HYDRA', 'ILLUSION', 'KOBOLD', 'KRAKEN',
    'LEVIATHAN', 'LICH', 'MAGE', 'MAGICIAN', 'MANTICORE', 'MEDUSA', 'MERMAID', 'MINOTAUR', 'MYTHICAL', 'NYMPH',
    'OGRE', 'ORACLE', 'ORC', 'PEGASUS', 'PHOENIX', 'PIXIE', 'POTION', 'PROPHECY', 'RUNES', 'SATYR',
    'SCROLL', 'SIREN', 'SORCERER', 'SPECTER', 'SPELLBOOK', 'SPHINX', 'SPRITE', 'STAFF', 'TALISMAN', 'TITAN',
    'TROLL', 'UNICORN', 'VALKYRIE', 'VAMPIRE', 'WARLOCK', 'WEREWOLF', 'WIGHT', 'WIZARD', 'WRAITH', 'WYRM',
    'WYVERN', 'ZEPHYR', 'ZOMBIE', 'VALHALLA', 'OLYMPUS', 'ASGARD', 'EXCALIBUR', 'MJOLNIR', 'GRIMOIRE', 'SEER',
    'MYSTIC', 'CHALICE', 'SHIELD', 'GAUNTLET', 'PALADIN', 'ARCHER', 'BERSERKER', 'AVALON', 'BANSHEE', 'CENTAUR',
    'CHIMERA', 'DRAKE', 'DROW', 'DRYAD', 'DURANDAL', 'EIDOLON', 'GORGON', 'HOBGOBLIN', 'HOMUNCULUS', 'HYDRID',
  ],

  'sports & games': [
    'ARCHERY', 'ARENA', 'ATHLETE', 'BADMINTON', 'BASEBALL', 'BATSMAN', 'BIATHLON', 'BILLIARDS', 'BOWLING', 'BOXING',
    'CHAMPION', 'COACH', 'CRICKET', 'CYCLING', 'DEFENDER', 'DERBY', 'DODGEBALL', 'DRIBBLE', 'DUATHLON', 'FENCING',
    'FIELD', 'FORWARD', 'GOLF', 'HANDBALL', 'HELMET', 'HURDLES', 'INNINGS', 'JAVELIN', 'JOCKEY', 'JUDO',
    'KARATE', 'KAYAKING', 'LACROSSE', 'LEAGUE', 'MARATHON', 'MEDAL', 'NETBALL', 'OFFENSE', 'OLYMPICS', 'PADDLE',
    'PENALTY', 'PLAYOFF', 'PODIUM', 'POLO', 'RACQUET', 'REFEREE', 'RELAY', 'ROWING', 'RUGBY', 'RUNNER',
    'SAILING', 'SCORING', 'SKATING', 'SKIING', 'SLALOM', 'SNOWBOARD', 'SOCCER', 'SPRINT', 'SQUASH', 'STADIUM',
    'STRIKER', 'SURFING', 'SWIMMING', 'TACTICS', 'TENNIS', 'TIMING', 'TRACK', 'TRIATHLON', 'TROPHY', 'UMPIRE',
    'VAULT', 'VELODROME', 'WICKET', 'WINNER', 'WRESTLING', 'YACHTING', 'ARCHER', 'BATTER', 'CADDIE', 'CAPTAIN',
    'DEFENSE', 'DRIFT', 'GOALIE', 'HEADER', 'PITCHER', 'ROOKIE', 'SLAM', 'TACKLE', 'BALL', 'BASKET',
    'CURLING', 'DARTBOARD', 'DRIBBLE', 'FREEKICK', 'GOALPOST', 'HALFTIME', 'HOMERUN', 'KICKOFF', 'OFFSIDE', 'PUNT',
  ],

  'music & audio': [
    'ACCORDION', 'ACOUSTIC', 'AMPLIFIER', 'BALLAD', 'BAND', 'BANJO', 'BASS', 'BASSOON', 'BEAT', 'BONGO',
    'BRASS', 'CELLO', 'CHOIR', 'CHORD', 'CLARINET', 'CLEF', 'COMPOSER', 'CONCERT', 'CORNET', 'CRESCENDO',
    'CYMBAL', 'DISCO', 'DRUMMER', 'DUET', 'ENSEMBLE', 'FIDDLE', 'FLUTE', 'FRETBOARD', 'FUGUE', 'GENRE',
    'GUITAR', 'HARMONICA', 'HARMONY', 'HARP', 'JAZZ', 'KEYBOARD', 'LUTE', 'LYRICS', 'MANDOLIN', 'MARACAS',
    'MELODY', 'METRONOME', 'MIXER', 'MOVEMENT', 'NOTATION', 'OBOE', 'OCTAVE', 'OPERA', 'ORCHESTRA', 'ORGAN',
    'OVERTURE', 'PIANIST', 'PITCH', 'QUARTET', 'RECITAL', 'RECORDING', 'REFRAIN', 'REVERB', 'RHYTHM', 'SAXOPHONE',
    'SCALE', 'SCORE', 'SINGER', 'SNARE', 'SOLOIST', 'SONATA', 'SOPRANO', 'STACCATO', 'STRINGS', 'SYMPHONY',
    'TEMPO', 'TENOR', 'TIMBRE', 'TIMPANI', 'TREBLE', 'TROMBONE', 'TRUMPET', 'TUBA', 'UKULELE', 'VIBRATO',
    'VIOLA', 'VIOLIN', 'VIRTUOSO', 'VOCALS', 'VOLUME', 'WALTZ', 'WOODWIND', 'XYLOPHONE', 'ALTO', 'AUDITORIUM',
    'BARITONE', 'BATON', 'BEATBOX', 'CANTATA', 'CAPO', 'CARILLON', 'CASTANETS', 'CHIME', 'CHORUS', 'CODA',
  ],

  'weather & seasons': [
    'AURORA', 'AUTUMN', 'AVALANCHE', 'BAROMETER', 'BLIZZARD', 'BREEZE', 'CELSIUS', 'CHILL', 'CIRRUS', 'CLIMATE',
    'CLOUD', 'CUMULUS', 'CYCLONE', 'DEWPOINT', 'DOWNPOUR', 'DRIZZLE', 'DROUGHT', 'FLOOD', 'FLURRY', 'FORECAST',
    'FREEZE', 'FRONT', 'FROST', 'GALE', 'GLACIER', 'GUST', 'HAILSTONE', 'HAZE', 'HUMIDITY', 'HURRICANE',
    'ICEBERG', 'ICICLE', 'ISOBAR', 'LIGHTNING', 'MIST', 'MONSOON', 'NIMBUS', 'OVERCAST', 'OZONE', 'PRESSURE',
    'RAINBOW', 'RAINFALL', 'RIME', 'SEASONS', 'SHOWER', 'SLEET', 'SMOG', 'SNOWDRIFT', 'SNOWFLAKE', 'SNOWSTORM',
    'SOLSTICE', 'SPRING', 'SQUALL', 'STRATUS', 'SUMMER', 'SUNBEAM', 'SUNSHINE', 'THUNDER', 'TORNADO', 'TSUNAMI',
    'TURBULENCE', 'TYPHOON', 'VAPOR', 'VORTEX', 'WARMTH', 'WINTER', 'ZEPHYR', 'ANEMOMETER', 'CLOUDBURST', 'DOWNDRAFT',
    'DUSTSTORM', 'HABOOB', 'HEATWAVE', 'JETSTREAM', 'NORTHERLY', 'SOUTHERLY', 'UPDRAFT', 'WHITE', 'WILDFIRE', 'AIRMASS',
    'BLUSTERY', 'CALM', 'CHILLY', 'DRIFT', 'DRIZZLY', 'FOGGY', 'FREEZING', 'FROSTY', 'GUSTY', 'HAZY',
    'HUMID', 'MILD', 'MUGGY', 'RAINY', 'STORMY', 'SUNNY', 'TEMPERATE', 'THAW', 'TROPICAL', 'WINTRY',
  ],

  'world & travel': [
    'AIRLINE', 'AIRPORT', 'ARRIVAL', 'ATLAS', 'BACKPACK', 'BORDER', 'BOULEVARD', 'BREEZE', 'CAPITAL', 'CARAVAN',
    'CASTLE', 'CITADEL', 'COMPASS', 'CONTINENT', 'CRUISE', 'CULTURE', 'CURRENCY', 'CUSTOMS', 'DEPARTURE', 'DIPLOMAT',
    'EMBASSY', 'EXPEDITION', 'EXPLORER', 'FERRY', 'FLIGHT', 'GLOBE', 'GUIDEBOOK', 'HARBOR', 'HERITAGE', 'HIGHWAY',
    'HORIZON', 'HOSTEL', 'HOTEL', 'ISLAND', 'ITINERARY', 'JOURNEY', 'LANDMARK', 'LATITUDE', 'LIGHTHOUSE', 'LOCALITY',
    'LONGITUDE', 'LUGGAGE', 'METROPOLIS', 'MONUMENT', 'MOSAIC', 'MOUNTAIN', 'NAVIGATION', 'NOMAD', 'OASIS', 'ODYSSEY',
    'OVERSEAS', 'PACKING', 'PANORAMA', 'PASSPORT', 'PENINSULA', 'PILGRIM', 'PROMENADE', 'RAILWAY', 'RESORT', 'ROADTRIP',
    'SAFARI', 'SCENERY', 'SEAPORT', 'SHUTTLE', 'SOJOURN', 'SOUVENIR', 'STATION', 'SUITCASE', 'SUNSET', 'TERMINAL',
    'TICKET', 'TOURIST', 'TOWNSHIP', 'TRACKING', 'TRANSIT', 'TRAVELER', 'TREKKING', 'TROPICS', 'VACATION', 'VALLEY',
    'VEHICLE', 'VIADUCT', 'VILLAGE', 'VISA', 'VOYAGE', 'WANDERLUST', 'WATERFALL', 'WAYFARER', 'WILDERNESS', 'WINDMILL',
    'WORLDWIDE', 'CARRIER', 'RUNWAY', 'ROADSIDE', 'AIRWAYS', 'ALCOVE', 'AVENUE', 'BLVD', 'CAMPER', 'CARGO',
  ],
};

export const DEFAULT_WORDS = THEMED_WORD_BANKS['space']!;

/**
 * Returns a list of deduplicated, valid uppercase words for a given theme.
 * If the theme matches one of the curated banks, returns that entire pool.
 * Otherwise returns the Space default pool.
 */
export function getWordsForTheme(theme: string): string[] {
  const key = theme.trim().toLowerCase();
  const exact = THEMED_WORD_BANKS[key];
  if (exact) return exact;
  for (const [name, words] of Object.entries(THEMED_WORD_BANKS)) {
    if (key.includes(name) || name.includes(key)) return words;
  }

  return DEFAULT_WORDS;
}

/** Backward-compatible alias */
export const fallbackWordsFor = getWordsForTheme;
